### ISSUE TITLE
No support for TensorFunctionSpaces

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#348]
Currently there is no support for TensorFunctionSpaces:

```
from firedrake import *
mesh = UnitSquareMesh(10, 10)
tfs = TensorFunctionSpace(mesh, "CG", 1)
```

```
Traceback (most recent call last):
  File "test_tensor.py", line 3, in <module>
    tfs = TensorFunctionSpace(mesh, "CG", 1)
NameError: name 'TensorFunctionSpace' is not defined
```

Please could TensorFunctionSpaces be added to the wishlist?

**Comment by ctjacobs** [comment]
Poke.

**Comment by ctjacobs** [comment]
After merging `master` into the `TFS` branch I now get a plex-related error which Michael also mentioned earlier today

```
christian@elevate /data $ python tensor.py 
pyop2:WARNING cachetools not available, expression assembly will be slowed down
Traceback (most recent call last):
  File "tensor.py", line 3, in <module>
    tfs = TensorFunctionSpace(mesh, "CG", 1)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_320_g556db5a-py2.7-linux-x86_64.egg/pyop2/caching.py", line 161, in __new__
    obj = make_obj()
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_320_g556db5a-py2.7-linux-x86_64.egg/pyop2/caching.py", line 142, in make_obj
    obj.__init__(*args, **kwargs)
  File "/data/firedrake/firedrake/functionspace.py", line 618, in __init__
    dim=shape, rank=2)
  File "/data/firedrake/firedrake/functionspace.py", line 107, in __init__
    perm=mesh._plex_renumbering)
AttributeError: 'Mesh' object has no attribute '_plex_renumbering'
```

which I've worked around by calling `mesh.init()` just before line 107 in functionspace.py. The code

```
from firedrake import *
mesh = UnitSquareMesh(10, 10)
tfs = TensorFunctionSpace(mesh, "CG", 1)
tensor_expression = Expression( ( ("1.0", "1.0"), ("1.0", "1.0") ) )
tensor_function = Function(tfs).interpolate(tensor_expression)
```

now fails when trying to call `ast.FlatBlock`

```
        ass_exp = [ast.Assign(ast.Symbol(A, (k,), ((len(expression.code), i),)),
                              ast.FlatBlock("%s" % code))
                   for i, code in enumerate(expression.code)]
```
```
Traceback (most recent call last):
  File "tensor.py", line 5, in <module>
    tensor_function = Function(tfs).interpolate(tensor_expression)
  File "/data/firedrake/firedrake/function.py", line 223, in interpolate
    subset)
  File "/data/firedrake/firedrake/function.py", line 267, in _interpolate
    to_pts, to_element, fs, coords)
  File "/data/firedrake/firedrake/function.py", line 335, in _interpolate_c_kernel
    for i, code in enumerate(expression.code)]
TypeError: not all arguments converted during string formatting
```

because COFFEE's `ast.FlatBlock` is being given a tuple rather than the single string it expects from `code`:

```
for i, code in enumerate(expression.code):
   print i, code
```
```
0 ('1.0', '1.0')
1 ('1.0', '1.0')
```

I tried adding another loop over the elements of the separate tuples and passing them individually to `ast.FlatBlock`:

```
        ass_exp = []
        for i, code in enumerate(expression.code):
           if(isinstance(code, tuple)):
              for j in range(len(code)):
                 ass_exp.append(ast.Assign(ast.Symbol(A, (k,), ((len(expression.code), i),)),
                              ast.FlatBlock("%s" % code[j])))
           else:
              ass_exp.append(ast.Assign(ast.Symbol(A, (k,), ((len(expression.code), i),)),
                              ast.FlatBlock("%s" % code)))
```

but I get another error further on down

```
Traceback (most recent call last):
  File "tensor.py", line 5, in <module>
    tensor_function = Function(tfs).interpolate(tensor_expression)
  File "/data/firedrake/firedrake/function.py", line 223, in interpolate
    subset)
  File "/data/firedrake/firedrake/function.py", line 267, in _interpolate
    to_pts, to_element, fs, coords)
  File "/data/firedrake/firedrake/function.py", line 390, in _interpolate_c_kernel
    [ast.Decl("double", ast.Symbol(A, (int("%(nfdof)d" % vals),))),
TypeError: %d format: a number is required, not tuple
```

**Comment by ggorman** [comment]
Can I +1 this as it's now slap-bang in our critical path for the IPCC/FWI project?

**Comment by mlange05** [comment]
I just pushed a tentative fix for the interpolate problem on the rebased `TFS` branch. @ctjacobs can you give this a try please?

**Comment by wence-** [comment]
I think I provided a better fix.  There are no tests, so it would be nice if someone could add some.

**Comment by ggorman** [comment]
@wence- is the fix you mention in master or TFS? 

@ctjacobs how about reusing your dolfin elastic wave equation as a test?

**Comment by wence-** [comment]
It is not in master, there are no tests.  I would like someone who is using this stuff to add them.  That involves not just "solving some random equation", but actually verifying that the different pieces work and building up to solving equations.  A non-exhaustive list of things:

- pointwise expressions involving tensor-valued functions
- interpolation of Expressions into tensor-valued functions
- 0-form assembly: e.g. computation of norms
- mass solves
- ...

**Comment by ctjacobs** [comment]
Thanks. I can confirm those fixes work nicely. I've added a few basic tests in `tests/regression`, but have marked some as `xfail`:

* Tensor functions don't appear to work with quadrilateral meshes, so I've marked the extended `test_math_functions` test which considers quads as `xfail` in `tests/regression/test_zero_forms.py`. Without `xfail`, the error message given is: https://gist.github.com/ctjacobs/5362bc086ce1176da565
* Cannot project onto a TensorFunctionSpace, so the new tests `test_tensor_convergence` and `run_tensor_test` are marked as `xfail` in `test_projection.py`.

These issues (as well as the issue of not being able to write tensor functions to a VTU file) aren't show-stoppers right now though.

**Comment by wence-** [comment]
So you can't build tensor finite elements on quad meshes because under the hood we'll need to support an OuterProductTensorElement (or similar) I guess.

**Comment by wence-** [comment]
Can you just fix the projection issue?  I think it's that project (in firedrake/projection.py) doesn't handle tensor-valued expressions.

**Comment by ctjacobs** [comment]
I think I've fixed it - `test_tensor_convergence` in `test_projection.py` is passing now without the `xfail` marker.

**Comment by wence-** [comment]
Can you add some tests of non-standard shaped tensors?  For example, there's no requirement that the shape even be of rank 2. For example:

```
V = TensorFunctionSpace(m, ..., shape=(2, 5, 3))
```

I suspect that everything will just run through and work.

As for IO, VTK supports tensor-valued fields, but it looks like the vtk writer we're using doesn't.  It's not clear to me if the vaguely in flight hdf5 stuff would help here.

**Comment by wence-** [comment]
Also, a few tests solving on tensor-valued spaces would be good.  Even if to begin with you just add some more identity tests (tests/regression/test_identity.py)

**Comment by wence-** [comment]
BTW, if this elastic wave equation can be MMSed and run in some reasonable time (i.e. under 30secs or so) you can happily include it.

**Comment by ctjacobs** [comment]
Just added some identity tests and two non-standard shaped tensor tests. I'm developing the elastic wave equation stuff in a separate repository and will leave that there for now. Shall I make a pull request for this branch?

**Comment by wence-** [comment]
Yes, I think this is in a state to be looked at.  I'll fix up the merge disaster :p

**Comment by wence-** [comment]
OK, if there are subsequent broken things, please raise separate issues.
